In [1]:
import cv2
import numpy as np

In [2]:
image = cv2.imread('./images/input.jpg')
B, G, R = cv2.split(image)
print(B)

[[171 170 170 ... 208 208 208]
 [170 170 170 ... 207 207 207]
 [170 170 170 ... 206 206 206]
 ...
 [ 90  77  57 ...   9   6   1]
 [ 96  97  66 ...   6   2   0]
 [ 99  92  76 ...   4   2   0]]


In [3]:
zeros = np.zeros(image.shape[:2], dtype = "uint8")

cv2.imshow("Red", cv2.merge([zeros,zeros,R ]))
cv2.imshow("Green", cv2.merge([zeros,G,zeros ]))
cv2.imshow("Blue", cv2.merge([B,zeros,zeros ]))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
cv2.imshow('Original', image)
cv2.waitKey()

In [5]:
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow('GrayScale', gray_image)
cv2.waitKey()
cv2.destroyAllWindows()